### ISSUE TITLE
Stops updating after a while

### ISSUE THREAD

**Issue by ericbodden** [michbeck100/pv-monitoring#5] opened 2023-04-23 17:43 UTC
Hi again.

After having tried your solution on my Mac, I have now installed it on a server. It also works mostly fine for several hours, but then after a while it always seems to somehow hang itself up. I see now further updates in the UI, and also the timestamp shown there is no longer updated.

Initially it helped to restart the Docker containers but now even that seems to be of no use. Do you have any idea how to rectify this?

Best wishes
Eric

**Comment by michbeck100** [comment] 2023-04-23 19:44
What scan interval are you using?

**Comment by ericbodden** [comment] 2023-04-24 09:30
I had been using 10s but I then extended it to 30s.

**Comment by ericbodden** [comment] 2023-04-24 11:10
I have had some more time to look into this. It seems like there is a more fundamental problem: by default "mosquitto" wants to use port 9001. On a fresh install I get:

``
Error response from daemon: driver failed programming external connectivity on endpoint mosquitto (6e9b505879295100e4eba7a98d9358b2183563fa2bb9c44f6923d813c2b6508a): Error starting userland proxy: listen tcp4 0.0.0.0:9001: bind: address already in use
``

I have tried changing the port to something else in docker-compose.yml, however, I am not sure this is correct or even makes sense.

Port 9001 is currently occupied by a HTML log viewer of OpenHAB, which is running on the same box.

**Comment by michbeck100** [comment] 2023-04-24 11:48
Just remove the port 9001 from the docker-compose.yml. It’s not needed really

**Comment by ericbodden** [comment] 2023-04-26 13:52
Hmmm okay. It's now running again but still gets regularly stuck and discontinues its updates. Do you know of a good way to debug this?

**Comment by michbeck100** [comment] 2023-04-26 14:01
If the updates stop, I would first check the modbus_proxy logs. If it contains errors then the problem is your inverter. 
It's known that too many updates will break the network stack of the inverter. This has been discussed here: https://www.photovoltaikforum.com/thread/170810-sungrow-hat-probleme-mit-der-modbus-verbindung/ 

I close this issue for now. If the problems come from the monitoring please reopen.

**Closed as completed by michbeck100** 2023-04-26 14:01 UTC
